repos:
-   repo: https://github.com/pycqa/isort
    rev: '5.10.1'
    hooks:
    -   id: isort
-   repo: https://github.com/hadialqattan/pycln
    rev: 'v2.1.1'
    hooks:
    -   id: pycln
        args: ['--all']
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: 'v2.0.0'
    hooks:
    -   id: autopep8
#-   repo: https://github.com/psf/black
#    rev: '22.10.0'
#    hooks:
#    -   id: black
#-   repo: https://gitlab.com/pycqa/flake8
#    rev: '3.9.2'
#    hooks:
#    -   id: flake8