version: '3.7'

services:

  base-backend:
    build: .
    ports:
      - 8000:8000
    command: uvicorn app.main:app --host 0.0.0.0 --reload
    restart: always
    depends_on:
      -  base-db

  #  nginx:
  #    build: ./nginx
  #    restart: unless-stopped
  #    depends_on:
  #      - backend
  #    ports:
  #      - 8080:80
  #    volumes:
  #      - ./nginx/snippets:/etc/nginx/snippets

  base-db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql
    env_file:
      - .env
    ports:
      - 5432:5432
    restart: always

  base-redis:
    image: redis:7
    restart: always
    ports:
      - 6379:6379

  base-worker:
    build: .
    restart: always
    command: celery -A app.celery_app.celery worker --loglevel=info
    volumes:
      - celery_data:/var/run/celery/
    env_file:
      - .env

  base-flower:
    build: .
    restart: always
    command: celery flower --broker="${CELERY_BROKER_URL}" --persistent=True --basic_auth="${CELERY_FLOWER_USER}:${CELERY_FLOWER_PASSWORD}"
    ports:
      - 5555:5555
    env_file:
      - .env

  celery-beat:
    build: .
    restart: always
    command: celery -A app.celery_app.celery beat -l info
    env_file:
      - .env

  base-rabbitmq:
    image: rabbitmq
    ports:
      - 5672:5672
    volumes:
      - rabbitmq_data:/var/lib/
    env_file:
      - .env
    restart: always

volumes:
  postgres_data:
  rabbitmq_data:
  celery_data: